import OpenAI from "openai";
import { env } from "../../../config/env.js";
import { AIRepository } from "../repositories/ai.repository.js";
import { logger } from "../../../config/logger.js";

const aiRepo = new AIRepository();
const openai = env.OPENAI_API_KEY
  ? new OpenAI({
      apiKey: env.OPENAI_API_KEY,
      baseURL: env.OPENAI_API_KEY.startsWith("sk-or-") ? "https://openrouter.ai/api/v1" : undefined,
    })
  : null;

const AI_DISCLAIMER = "\n\n---\n*This response was generated by AI and should be reviewed by a qualified medical professional before use.*";

export class AIService {
  async chat(userId: string, message: string) {
    if (!openai) return { reply: "AI service is not configured. Please set OPENAI_API_KEY.", isAIGenerated: false };

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: "You are a medical AI assistant helping clinic staff. Provide helpful, accurate information. Always include a disclaimer that you are AI and not a replacement for professional medical advice." },
        { role: "user", content: message },
      ],
      max_tokens: 1024,
    });

    const reply = completion.choices[0]?.message?.content || "No response generated.";
    const responseWithDisclaimer = reply + AI_DISCLAIMER;

    await aiRepo.create({ userId, requestType: "chat", prompt: message, response: reply, wasApproved: null });
    logger.info({ event: "ai_chat", userId });

    return { reply: responseWithDisclaimer, isAIGenerated: true };
  }

  async analyzeSymptoms(userId: string, symptoms: string[], _patientId?: string) {
    if (!openai) return { analysis: "AI service not configured.", isAIGenerated: false };

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: "You are a medical assistant. Analyze the given symptoms and provide possible causes, recommended tests, and general advice. Include an AI disclaimer." },
        { role: "user", content: `Symptoms: ${symptoms.join(", ")}` },
      ],
      max_tokens: 1024,
    });

    const analysis = completion.choices[0]?.message?.content || "Unable to analyze.";
    const responseWithDisclaimer = analysis + AI_DISCLAIMER;

    await aiRepo.create({ userId, requestType: "symptom_analysis", prompt: symptoms.join(", "), response: analysis, wasApproved: null });
    logger.info({ event: "ai_symptom_analysis", userId });

    return { analysis: responseWithDisclaimer, isAIGenerated: true };
  }

  async suggestDiagnosis(userId: string, symptoms: string[], testResults?: string, patientHistory?: string) {
    if (!openai) return { suggestions: "AI service not configured.", isAIGenerated: false };

    const prompt = `Symptoms: ${symptoms.join(", ")}\nTest Results: ${testResults || "N/A"}\nPatient History: ${patientHistory || "N/A"}`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: "You are a diagnostic assistant. Suggest possible diagnoses based on symptoms, test results, and history. Rank by likelihood. Include an AI disclaimer." },
        { role: "user", content: prompt },
      ],
      max_tokens: 1024,
    });

    const suggestions = completion.choices[0]?.message?.content || "Unable to suggest.";
    const responseWithDisclaimer = suggestions + AI_DISCLAIMER;

    await aiRepo.create({ userId, requestType: "diagnosis_suggestion", prompt, response: suggestions, wasApproved: null });
    logger.info({ event: "ai_diagnosis_suggestion", userId });

    return { suggestions: responseWithDisclaimer, isAIGenerated: true };
  }

  async draftPrescription(userId: string, diagnosis: string, _patientId: string, _doctorId: string) {
    if (!openai) return { draft: "AI service not configured.", isAIGenerated: false };

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: "You are a medical assistant. Draft a prescription for the given diagnosis. Include medication name, dosage, frequency, and duration. Mark it as AI-generated. Include an AI disclaimer." },
        { role: "user", content: `Diagnosis: ${diagnosis}` },
      ],
      max_tokens: 1024,
    });

    const draft = completion.choices[0]?.message?.content || "Unable to draft.";
    const responseWithDisclaimer = draft + `\n\n**AI-Generated Draft** — Requires doctor approval before use.`;

    await aiRepo.create({ userId, requestType: "prescription_draft", prompt: diagnosis, response: draft, wasApproved: null });
    logger.info({ event: "ai_prescription_draft", userId });

    return { draft: responseWithDisclaimer, isAIGenerated: true, requiresDoctorApproval: true };
  }
}
